export const productsData = [
  {
    id: 1,
    title: "app1",
    price: 10.99,
    imageUrl: "./images/app1.jpg",
    quantity: 1,
  },
  {
    id: 2,
    title: "app2",
    price: 9.49,
    imageUrl: "./images/app2.jpg",
    quantity: 1,
  },
  {
    id: 3,
    title: "app3",
    price: 7.29,
    imageUrl: "./images/app3.jpg",
    quantity: 1,
  },
  {
    id: 4,
    title: "graphic1",
    price: 2.99,
    imageUrl: "./images/graphic1.jpg",
    quantity: 1,
  },
  {
    id: 5,
    title: "graphic2",
    price: 3.99,
    imageUrl: "./images/graphic2.jpg",
    quantity: 1,
  },
  {
    id: 6,
    title: "graphic3",
    price: 2.53,
    imageUrl: "./images/graphic3.jpg",
    quantity: 1,
  },
  {
    id: 7,
    title: "web1",
    price: 6.25,
    imageUrl: "./images/web1.jpg",
    quantity: 1,
  },
  {
    id: 8,
    title: "web2",
    price: 5.25,
    imageUrl: "./images/web2.jpg",
    quantity: 1,
  },
  {
    id: 9,
    title: "web3",
    price: 4.25,
    imageUrl: "./images/web3.jpg",
    quantity: 1,
  },
];
